### ISSUE TITLE
mt_rand(): max(0) is smaller than min(1)

### ISSUE THREAD

**Issue by dktapps** [Xenophilicy/OreGen#1] opened 2019-01-28 08:46 UTC
https://crash.pmmp.io/view/2117943

[2117943.log](https://github.com/Xenophilicy/OreGen/files/2802073/2117943.log)

**Comment by Xenophilicy** [comment] 2019-01-28 23:14
Hello @dktapps,

I'm sorry you've run into an issue using my plugin OreGen. 

I believe the issue is that your probability integer was set too low (too close to 0 such as 0.4). This would cause your integer to round down to 0, making the minimum and maximum for the random number both 0. If that's the case, this will help me develop a bit of code to warn the user if the probability is set too low.

Would you mind sending me the contents of your settings.yml? This will help me confirm and find the source of your issue. Thanks!

**Comment by dktapps** [comment] 2019-01-29 08:35
This is not my issue. It just appeared in the crash archive today. The bug looks trivial to fix.

**Comment by Xenophilicy** [comment] 2019-01-29 14:12
Ok, have you tried updating your pocketmine.phar yet? (I assume you have because you're the one developing it) If you've already done that, what do you have your probability integer set to?

**Comment by dktapps** [comment] 2019-01-29 14:43
Have you tried reading? I said this is not my issue.

**Comment by SOF3** [comment] 2019-01-29 14:47
Whatever appears in the config, it is the responsibility of the developer to validate it.

**Comment by Xenophilicy** [comment] 2019-01-29 17:15
@dktapps,

Hello. I am very sorry, I did not read your comment correctly as it was early in the morning so please excuse that. Do you then know who the owner of the crash log is? If so, would you give me a way to contact them so I may direct them to the correct way to fix the issue? Although my guess is that they have already resolved it since there was only one crash report with that error. Thanks, and my apologies again for misunderstanding you.

After this is cleared up, I will push an update so that this issue can be prevented by checking if the probablity integer is over a certain amount, and if not, throw an error asking the user to check their probability. 

Thank you once again for sending this to me.

**Comment by SOF3** [comment] 2019-01-30 02:24
The crash log is anonymous. We are not CIA.

**Comment by Xenophilicy** [comment] 2019-01-30 04:36
**Problem was addressed and resolved in an update. Update was pushed to [Poggit](https://poggit.pmmp.io/p/OreGen/1.0.3).**

**Closed as completed by Xenophilicy** 2019-01-30 04:36 UTC
Labels: bug
